### ISSUE TITLE
Loading multiple files not working

### ISSUE THREAD

**Issue by tashi21** [hyperjumptech/grule-rule-engine#310]
**Describe the bug**

Loading rules using ```pkg.NewFileResourceBundle()``` results in:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x627659]

goroutine 1 [running]:
github.com/hyperjumptech/grule-rule-engine/engine.(*GruleEngine).ExecuteWithContext(0xc00011de20, {0x801a68, 0xc000022088}, {0x805fb0?, 0xc00015ec00}, 0x0?)   
        C:/Users/tashi/go/pkg/mod/github.com/hyperjumptech/grule-rule-engine@v1.10.6/engine/GruleEngine.go:86 +0x59
github.com/hyperjumptech/grule-rule-engine/engine.(*GruleEngine).Execute(...)
        C:/Users/tashi/go/pkg/mod/github.com/hyperjumptech/grule-rule-engine@v1.10.6/engine/GruleEngine.go:52
main.main()
        C:/Users/tashi/go/src/gitlab.com/raaho/fin-service/main.go:47 +0x2f0
```

**To Reproduce**

1. I have copied the tutorial code and tried to load the rules from an external .grl file. I used ```pkg.NewFileResourceBundle()``` to load it.
2. Instead of running without errors and printing the updated fact, I see the given error.

**Expected behavior**

The code compiles without errors and displays updated fact.

**Additional context**
My directory:

```
- main.go
- rules/
  - test.grl
```

**Comment by newm4n** [comment]
Hi @tashi21 

Sorry for this very late late response...
Could you show the code snippet where you use `NewFileResourceBundle` function ?
